/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

/**
 *
 * @author USER
 */
public class FormPrint extends javax.swing.JPanel {

    /**
     * Creates new form FormPrint
     */
    public FormPrint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pn_menuPrint = new javax.swing.JPanel();
        print_pembayaran = new javax.swing.JButton();
        print_pemeriksaan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        print_pembayaran.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        print_pembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Payment_History_60px.png"))); // NOI18N
        print_pembayaran.setText("Pembayaran");

        print_pemeriksaan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        print_pemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_health_checkup_60px.png"))); // NOI18N
        print_pemeriksaan.setText("Pemeriksaan");
        print_pemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_pemeriksaanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/print.png"))); // NOI18N
        jLabel1.setText("Print Out");

        javax.swing.GroupLayout pn_menuPrintLayout = new javax.swing.GroupLayout(pn_menuPrint);
        pn_menuPrint.setLayout(pn_menuPrintLayout);
        pn_menuPrintLayout.setHorizontalGroup(
            pn_menuPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuPrintLayout.createSequentialGroup()
                .addGroup(pn_menuPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_menuPrintLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(print_pemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(print_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_menuPrintLayout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        pn_menuPrintLayout.setVerticalGroup(
            pn_menuPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuPrintLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_menuPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(print_pemeriksaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(print_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(255, Short.MAX_VALUE))
        );

        mainPanel.add(pn_menuPrint, "card2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel2, "card3");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void print_pemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_pemeriksaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_print_pemeriksaanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_menuPrint;
    private javax.swing.JButton print_pembayaran;
    private javax.swing.JButton print_pemeriksaan;
    // End of variables declaration//GEN-END:variables
}
