/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

/**
 *
 * @author LENOVO
 */
public class FormPemeriksaan extends javax.swing.JPanel {

    /**
     * Creates new form FormDokter
     */
    public FormPemeriksaan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pn_dataPemeriksaan = new javax.swing.JPanel();
        pn_formPemeriksaan = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pn_dataPemeriksaanLayout = new javax.swing.GroupLayout(pn_dataPemeriksaan);
        pn_dataPemeriksaan.setLayout(pn_dataPemeriksaanLayout);
        pn_dataPemeriksaanLayout.setHorizontalGroup(
            pn_dataPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        pn_dataPemeriksaanLayout.setVerticalGroup(
            pn_dataPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        mainPanel.add(pn_dataPemeriksaan, "card2");

        javax.swing.GroupLayout pn_formPemeriksaanLayout = new javax.swing.GroupLayout(pn_formPemeriksaan);
        pn_formPemeriksaan.setLayout(pn_formPemeriksaanLayout);
        pn_formPemeriksaanLayout.setHorizontalGroup(
            pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        pn_formPemeriksaanLayout.setVerticalGroup(
            pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        mainPanel.add(pn_formPemeriksaan, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_dataPemeriksaan;
    private javax.swing.JPanel pn_formPemeriksaan;
    // End of variables declaration//GEN-END:variables
}
