/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

/**
 *
 * @author LENOVO
 */
public class FormKhitan extends javax.swing.JPanel {

    /**
     * Creates new form FormDokter
     */
    public FormKhitan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pn_dataKhitan = new javax.swing.JPanel();
        pn_formKhitan = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pn_dataKhitanLayout = new javax.swing.GroupLayout(pn_dataKhitan);
        pn_dataKhitan.setLayout(pn_dataKhitanLayout);
        pn_dataKhitanLayout.setHorizontalGroup(
            pn_dataKhitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        pn_dataKhitanLayout.setVerticalGroup(
            pn_dataKhitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        mainPanel.add(pn_dataKhitan, "card2");

        javax.swing.GroupLayout pn_formKhitanLayout = new javax.swing.GroupLayout(pn_formKhitan);
        pn_formKhitan.setLayout(pn_formKhitanLayout);
        pn_formKhitanLayout.setHorizontalGroup(
            pn_formKhitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        pn_formKhitanLayout.setVerticalGroup(
            pn_formKhitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        mainPanel.add(pn_formKhitan, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_dataKhitan;
    private javax.swing.JPanel pn_formKhitan;
    // End of variables declaration//GEN-END:variables
}
