/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import connection.connect;

/**
 *
 * @author LENOVO
 */
public class FormObat extends javax.swing.JPanel {

    private Connection conn = new connect().connect();
    private DefaultTableModel tabmode;

    /**
     * Creates new form FormDokter
     */
    public FormObat() {
        initComponents();
        datatable();
    }

    private void aktif() {
        tnamaobat.setEnabled(true);
        tkodeobat.setEnabled(true);
        tjenisobat.setEnabled(true);
        tstokobat.setEnabled(true);
        tharga.setEnabled(true);
        tnamaobat.requestFocus();
    }

    private void clear() {
        tnamaobat.setText("");
        tkodeobat.setText("");
        tjenisobat.setText("");
        tstokobat.setText("");
        tharga.setText("");
    }

    protected void datatable() {
        Object[] clcis = {"Nama Obat", "Kode Obat", "Jenis", "Stok", "Harga"};
        tabmode = new DefaultTableModel(null, clcis);
        tabelobat.setModel(tabmode);
        String sql = "select * from obat";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("Nama");
                String b = hasil.getString("Kode");
                String c = hasil.getString("Satuan");
                String d = hasil.getString("Stok");
                String e = hasil.getString("Harga");

                String[] data = {a, b, c, d, e};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pn_dataObat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelobat = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        bt_tambah = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        bt_kembali = new javax.swing.JButton();
        pn_formObat = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tnamaobat = new javax.swing.JTextField();
        tstokobat = new javax.swing.JTextField();
        tharga = new javax.swing.JTextField();
        tkodeobat = new javax.swing.JTextField();
        bback = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tjenisobat = new javax.swing.JTextField();
        bt_edit1 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        pn_dataObat.setBackground(new java.awt.Color(204, 204, 204));

        tabelobat.setBackground(new java.awt.Color(242, 242, 242));
        tabelobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelobatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelobat);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Data Obat");

        bt_tambah.setBackground(new java.awt.Color(242, 242, 242));
        bt_tambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_tambah.setText("Tambah");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        bt_hapus.setBackground(new java.awt.Color(242, 242, 242));
        bt_hapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_hapus.setText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        bt_kembali.setBackground(new java.awt.Color(242, 242, 242));
        bt_kembali.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_kembali.setText("Kembali");
        bt_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_dataObatLayout = new javax.swing.GroupLayout(pn_dataObat);
        pn_dataObat.setLayout(pn_dataObatLayout);
        pn_dataObatLayout.setHorizontalGroup(
            pn_dataObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dataObatLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_dataObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_dataObatLayout.createSequentialGroup()
                        .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_dataObatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_dataObatLayout.setVerticalGroup(
            pn_dataObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_dataObatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(pn_dataObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(241, 241, 241))
        );

        mainPanel.add(pn_dataObat, "card2");

        pn_formObat.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("News701 BT", 1, 36)); // NOI18N
        jLabel1.setText("Input Data Obat");

        jLabel4.setFont(new java.awt.Font("News701 BT", 1, 18)); // NOI18N
        jLabel4.setText("Nama Obat");

        jLabel5.setFont(new java.awt.Font("News701 BT", 1, 18)); // NOI18N
        jLabel5.setText("Jenis");

        jLabel6.setFont(new java.awt.Font("News701 BT", 1, 18)); // NOI18N
        jLabel6.setText("Kode Obat");

        jLabel7.setFont(new java.awt.Font("News701 BT", 1, 18)); // NOI18N
        jLabel7.setText("Harga");

        tnamaobat.setBackground(new java.awt.Color(242, 242, 242));

        tstokobat.setBackground(new java.awt.Color(242, 242, 242));
        tstokobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tstokobatActionPerformed(evt);
            }
        });

        tharga.setBackground(new java.awt.Color(242, 242, 242));

        tkodeobat.setBackground(new java.awt.Color(242, 242, 242));

        bback.setBackground(new java.awt.Color(242, 242, 242));
        bback.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bback.setText("Kembali");
        bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbackActionPerformed(evt);
            }
        });

        bsimpan.setBackground(new java.awt.Color(242, 242, 242));
        bsimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("News701 BT", 1, 18)); // NOI18N
        jLabel8.setText("Stok");

        tjenisobat.setBackground(new java.awt.Color(242, 242, 242));
        tjenisobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjenisobatActionPerformed(evt);
            }
        });

        bt_edit1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_edit1.setText("Edit");
        bt_edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_edit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_formObatLayout = new javax.swing.GroupLayout(pn_formObat);
        pn_formObat.setLayout(pn_formObatLayout);
        pn_formObatLayout.setHorizontalGroup(
            pn_formObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_formObatLayout.createSequentialGroup()
                .addGroup(pn_formObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_formObatLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(pn_formObatLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(pn_formObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_formObatLayout.createSequentialGroup()
                                .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bback)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_formObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(tharga, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addComponent(tkodeobat, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                                .addComponent(tnamaobat)
                                .addComponent(tjenisobat, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                                .addComponent(tstokobat)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pn_formObatLayout.setVerticalGroup(
            pn_formObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_formObatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tnamaobat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tkodeobat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tjenisobat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tstokobat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tharga, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(pn_formObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bback, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(pn_formObat, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String nama = tnamaobat.getText();
        String kode = tkodeobat.getText();
        String jenis = tjenisobat.getText();
        String stok = tstokobat.getText();
        String harga = tharga.getText();

        String sql = "INSERT INTO OBAT (Nama,Kode,Satuan,Stok,Harga ) VALUES (?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, nama);
            stat.setString(2, kode);
            stat.setString(3, jenis);
            stat.setString(4, stok);
            stat.setString(5, harga);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            clear();
            tnamaobat.requestFocus();
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan " + e);
        }
    }

    private void ideleteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }//GEN-LAST:event_bsimpanActionPerformed

    private void tstokobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tstokobatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tstokobatActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(pn_formObat);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void bt_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_kembaliActionPerformed
        mainPanel.removeAll();
        mainPanel.add(new content_bg());
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bt_kembaliActionPerformed

    private void tjenisobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjenisobatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tjenisobatActionPerformed

    private void bbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbackActionPerformed
        mainPanel.removeAll();
        mainPanel.add(pn_dataObat);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bbackActionPerformed

    private void tabelobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelobatMouseClicked
        int clc = tabelobat.getSelectedRow();
        String a = tabmode.getValueAt(clc, 0).toString();
        String b = tabmode.getValueAt(clc, 1).toString();
        String c = tabmode.getValueAt(clc, 2).toString();
        String d = tabmode.getValueAt(clc, 3).toString();
        String e = tabmode.getValueAt(clc, 4).toString();

        tnamaobat.setText(a);
        tkodeobat.setText(b);
        tjenisobat.setText(c);
        tstokobat.setText(d);
        tharga.setText(e);
    }//GEN-LAST:event_tabelobatMouseClicked

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0) {
            String sql = "delete from obat where Nama='" + tnamaobat.getText() + "'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasi dihapus");;
                clear();
                tnamaobat.requestFocus();
                datatable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data gagal dihapus" + e);
            }
        }
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_edit1ActionPerformed
    try {
            String sql = "update obat set Nama=?,Kode=?,Satuan=?,Stok=?,Harga=? where Nama=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tnamaobat.getText());
            stat.setString(2, tkodeobat.getText());
            stat.setString(3, tjenisobat.getText());
            stat.setString(4, tstokobat.getText());
            stat.setString(5, tharga.getText());
            
            stat.setString(6, tnamaobat.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            clear();
            tnamaobat.requestFocus();
            datatable();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah" + e);
        }
    }//GEN-LAST:event_bt_edit1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bback;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bt_edit1;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_kembali;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_dataObat;
    private javax.swing.JPanel pn_formObat;
    private javax.swing.JTable tabelobat;
    private javax.swing.JTextField tharga;
    private javax.swing.JTextField tjenisobat;
    private javax.swing.JTextField tkodeobat;
    private javax.swing.JTextField tnamaobat;
    private javax.swing.JTextField tstokobat;
    // End of variables declaration//GEN-END:variables
}
