/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import tablesearch.cariPasienCheck;
import tablesearch.cariPasien;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import connection.connect;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import tablesearch.cariDokterCheck;
import tablesearch.cariObatCheck;

/**
 *
 * @author LENOVO
 */
public class FormPemeriksaan extends javax.swing.JPanel {

    private Connection conn = new connect().connect();
    private DefaultTableModel tabmode;
    public String tidpas, tnama, tumur, tjk, tndok, tspc, tiddok, tidobat, tnamaobat;

    public String getIdPas() {
        return tidpas;
    }

    public String getIdOb() {
        return tidobat;
    }

    public String getIdNamaOb() {
        return tnamaobat;
    }

    public String getIdDok() {
        return tiddok;
    }

    public String getNamaPas() {
        return tnama;
    }

    public String getUmurPas() {
        return tumur;
    }

    public String getJkPas() {
        return tjk;
    }

    public String getNamaDok() {
        return tndok;
    }

    public String getSpcDok() {
        return tspc;
    }

    public void obatTerpilih() {
        cariObatCheck co = new cariObatCheck();
        co.check = this;
        idobat.setText(tidobat);
        resep.setText(tnamaobat);
    }

    public void dokterTerpilih() {
        cariDokterCheck cd = new cariDokterCheck();
        cd.check = this;
        iddok.setText(tiddok);
        nmdokter.setText(tndok);
        spcl.setText(tspc);
    }

    public void pasienTerpilih() {
        cariPasien cp = new cariPasien();
        cp.check = this;
        nama.setText(tidpas);
        idpas.setText(tnama);
        usia.setText(tumur);
        jk.setText(tjk);
    }

    public FormPemeriksaan() {
        initComponents();
        datatable();
    }

    private void aktif() {
        idpas.setEnabled(true);
        tgl.setEnabled(true);
        usia.setEnabled(true);
        jk.setEnabled(true);
        nmdokter.setEnabled(true);
        spcl.setEnabled(true);
        bb.setEnabled(true);
        tb.setEnabled(true);
        td.setEnabled(true);
        keluhan.setEnabled(true);
        diagnosa.setEnabled(true);
        resep.setEnabled(true);
        idpas.requestFocus();
    }

    private void clear() {
        idpas.setText("");
        tgl.setDate(null);
        usia.setText("");
        jk.setText("");
        nmdokter.setText("");
        spcl.setText("");
        bb.setText("");
        tb.setText("");
        td.setText("");
        keluhan.setText("");
        diagnosa.setText("");
        resep.setText("");
    }

    protected void datatable() {
        Object[] clcis = {"PasienId", "Tanggal", "TekananDarah", "Diagnosa", "ObatId"};
        tabmode = new DefaultTableModel(null, clcis);
        tpemeriksaan.setModel(tabmode);
        String sql = "select * from pemeriksaan";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("PasienId");
                String b = hasil.getString("Tanggal");
                String c = hasil.getString("TekananDarah");
                String d = hasil.getString("Diagnosa");
                String e = hasil.getString("ObatId");

                String[] data = {a, b, c, d, e};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pn_dataPemeriksaan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        bt_kembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpemeriksaan = new javax.swing.JTable();
        pn_formPemeriksaan = new javax.swing.JPanel();
        cari2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        spcl = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        td = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        keluhan = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        idpas = new javax.swing.JTextField();
        cari1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        diagnosa = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        usia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tgl = new com.toedter.calendar.JDateChooser();
        nmdokter = new javax.swing.JTextField();
        jk = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        iddok = new javax.swing.JTextField();
        resep = new javax.swing.JTextField();
        cari3 = new javax.swing.JButton();
        idobat = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Data Pemeriksaan");

        tambah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        bt_hapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bt_hapus.setText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        bt_kembali.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bt_kembali.setText("Kembali");
        bt_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_kembaliActionPerformed(evt);
            }
        });

        tpemeriksaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tpemeriksaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpemeriksaanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tpemeriksaan);

        javax.swing.GroupLayout pn_dataPemeriksaanLayout = new javax.swing.GroupLayout(pn_dataPemeriksaan);
        pn_dataPemeriksaan.setLayout(pn_dataPemeriksaanLayout);
        pn_dataPemeriksaanLayout.setHorizontalGroup(
            pn_dataPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dataPemeriksaanLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pn_dataPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pn_dataPemeriksaanLayout.createSequentialGroup()
                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(630, Short.MAX_VALUE))
            .addGroup(pn_dataPemeriksaanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pn_dataPemeriksaanLayout.setVerticalGroup(
            pn_dataPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dataPemeriksaanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(pn_dataPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        mainPanel.add(pn_dataPemeriksaan, "card2");

        cari2.setText("Cari");
        cari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Specialis");

        spcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spclActionPerformed(evt);
            }
        });

        jLabel9.setText("BB (KG)");

        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });

        jLabel10.setText("TB(cm)");

        tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbActionPerformed(evt);
            }
        });

        jLabel11.setText("Tekanan Darah");

        jLabel12.setText("Keluhan");

        jLabel13.setText("Diagnosa");

        jLabel2.setText("Input Pemeriksaan");

        jLabel14.setText("Resep Obat");

        jLabel3.setText("Tanggal pemeriksaan");

        keluhan.setColumns(20);
        keluhan.setRows(5);
        jScrollPane2.setViewportView(keluhan);

        jLabel4.setText("Nama Pasien");

        idpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpasActionPerformed(evt);
            }
        });

        cari1.setText("Cari");
        cari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari1ActionPerformed(evt);
            }
        });

        diagnosa.setColumns(20);
        diagnosa.setRows(5);
        jScrollPane3.setViewportView(diagnosa);

        jLabel5.setText("Usia");

        jLabel6.setText("Jenis Kelamin");

        simpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        kembali.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        jLabel7.setText("Nama Dokter");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        cari3.setText("Cari");
        cari3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_formPemeriksaanLayout = new javax.swing.GroupLayout(pn_formPemeriksaan);
        pn_formPemeriksaan.setLayout(pn_formPemeriksaanLayout);
        pn_formPemeriksaanLayout.setHorizontalGroup(
            pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                        .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                                .addGap(523, 523, 523)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                                    .addComponent(nmdokter, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(iddok, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cari2))
                                .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                                    .addComponent(nama)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idpas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cari1))
                                .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(usia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                        .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                                        .addGap(523, 523, 523)
                                        .addComponent(tgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_formPemeriksaanLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(287, 287, 287)
                                        .addComponent(jLabel13)
                                        .addGap(267, 267, 267)))
                                .addGap(14, 14, 14)
                                .addComponent(jLabel14))
                            .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(57, 57, 57))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_formPemeriksaanLayout.createSequentialGroup()
                                        .addComponent(spcl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(16, 16, 16)
                                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(td, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(resep, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idobat, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cari3))
                            .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                                .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kembali)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_formPemeriksaanLayout.setVerticalGroup(
            pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4))
                    .addGroup(pn_formPemeriksaanLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idpas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari1)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nmdokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari2)
                    .addComponent(iddok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spcl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(td, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(0, 0, 0)
                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(resep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cari3)
                        .addComponent(idobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_formPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        mainPanel.add(pn_formPemeriksaan, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(pn_formPemeriksaan);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_tambahActionPerformed

    private void cari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2ActionPerformed
        cariDokterCheck cd = new cariDokterCheck();
        cd.check = this;
        cd.setVisible(true);
        cd.setResizable(false);
        iddok.setEnabled(false);
        nmdokter.setEnabled(false);
        spcl.setEnabled(false);
    }//GEN-LAST:event_cari2ActionPerformed

    private void spclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spclActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spclActionPerformed

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbActionPerformed

    private void tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbActionPerformed

    private void idpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpasActionPerformed

    private void cari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari1ActionPerformed
        cariPasienCheck cp = new cariPasienCheck();
        cp.check = this;
        cp.setVisible(true);
        cp.setResizable(false);
        nama.setEnabled(false);
        idpas.setEnabled(false);
        usia.setEnabled(false);
        jk.setEnabled(false);
    }//GEN-LAST:event_cari1ActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String idpass = idpas.getText();
        String napes = nama.getText();
        java.util.Date date = tgl.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String umur = usia.getText();
        String jenkel = jk.getText();
        String tgl_periksa = sdf.format(date);
        String iddokk = iddok.getText();
        String special = spcl.getText();
        String berat = bb.getText();
        String tinggi = tb.getText();
        String tekanan = td.getText();
        String ngeluh = keluhan.getText();
        String diag = diagnosa.getText();
        String obat = idobat.getText();

        String sql = "INSERT INTO pemeriksaan (PasienId,Tanggal, Tb, Bb, Diagnosa, ObatId, IdDokter, TekananDarah,keluhan) VALUES (?, ?, ?, ?, ?, ?, ?,?,?)";

        try {
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, idpass);
            pst.setString(2, tgl_periksa);
            pst.setString(7, iddokk);
            pst.setString(4, berat);
            pst.setString(3, tinggi);
            pst.setString(8, tekanan);
            pst.setString(5, diag);
            pst.setString(6, obat);
            pst.setString(9, ngeluh);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data Pemeriksaan berhasil disimpan", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
            clear();
            idpas.requestFocus();
            datatable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Kesalahan database: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        mainPanel.removeAll();
        mainPanel.add(pn_dataPemeriksaan);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_kembaliActionPerformed

    private void bt_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_kembaliActionPerformed
        mainPanel.removeAll();
        mainPanel.add(new content_bg());
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bt_kembaliActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void cari3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari3ActionPerformed
        cariObatCheck co = new cariObatCheck();
        co.check = this;
        co.setVisible(true);
        co.setResizable(false);
        resep.setEnabled(false);
        idobat.setEnabled(false);
    }//GEN-LAST:event_cari3ActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0) {
            String sql = "delete from pemeriksaan where PasienId ='" + idpas.getText() + "'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasi dihapus");;
                clear();
                idpas.requestFocus();
                datatable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data gagal dihapus" + e);
            }
        }
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void tpemeriksaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpemeriksaanMouseClicked
        int row = tpemeriksaan.getSelectedRow();

        if (row >= 0 && row < tpemeriksaan.getRowCount()) {
            String id = tpemeriksaan.getValueAt(row, 0).toString();
//            String nama = tpemeriksaan.getValueAt(row, 1).toString();

            idpas.setText(id);
//            nama.setText(nama);

        } else {
            JOptionPane.showMessageDialog(null, "Pilihan tidak valid", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tpemeriksaanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bb;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_kembali;
    private javax.swing.JButton cari1;
    private javax.swing.JButton cari2;
    private javax.swing.JButton cari3;
    private javax.swing.JTextArea diagnosa;
    private javax.swing.JTextField iddok;
    private javax.swing.JTextField idobat;
    private javax.swing.JTextField idpas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jk;
    private javax.swing.JTextArea keluhan;
    private javax.swing.JButton kembali;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nmdokter;
    private javax.swing.JPanel pn_dataPemeriksaan;
    private javax.swing.JPanel pn_formPemeriksaan;
    private javax.swing.JTextField resep;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField spcl;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tb;
    private javax.swing.JTextField td;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JTable tpemeriksaan;
    private javax.swing.JTextField usia;
    // End of variables declaration//GEN-END:variables
}
