/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

/**
 *
 * @author LENOVO
 */
public class FormPembayaran extends javax.swing.JPanel {

    /**
     * Creates new form FormDokter
     */
    public FormPembayaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pn_dataPembayaran = new javax.swing.JPanel();
        pn_formPembayaran = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pn_dataPembayaranLayout = new javax.swing.GroupLayout(pn_dataPembayaran);
        pn_dataPembayaran.setLayout(pn_dataPembayaranLayout);
        pn_dataPembayaranLayout.setHorizontalGroup(
            pn_dataPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        pn_dataPembayaranLayout.setVerticalGroup(
            pn_dataPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        mainPanel.add(pn_dataPembayaran, "card2");

        javax.swing.GroupLayout pn_formPembayaranLayout = new javax.swing.GroupLayout(pn_formPembayaran);
        pn_formPembayaran.setLayout(pn_formPembayaranLayout);
        pn_formPembayaranLayout.setHorizontalGroup(
            pn_formPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        pn_formPembayaranLayout.setVerticalGroup(
            pn_formPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        mainPanel.add(pn_formPembayaran, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_dataPembayaran;
    private javax.swing.JPanel pn_formPembayaran;
    // End of variables declaration//GEN-END:variables
}
