/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

/**
 *
 * @author LENOVO
 */
public class FormObat extends javax.swing.JPanel {

    /**
     * Creates new form FormDokter
     */
    public FormObat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pn_dataObat = new javax.swing.JPanel();
        pn_formObat = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pn_dataObatLayout = new javax.swing.GroupLayout(pn_dataObat);
        pn_dataObat.setLayout(pn_dataObatLayout);
        pn_dataObatLayout.setHorizontalGroup(
            pn_dataObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        pn_dataObatLayout.setVerticalGroup(
            pn_dataObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        mainPanel.add(pn_dataObat, "card2");

        javax.swing.GroupLayout pn_formObatLayout = new javax.swing.GroupLayout(pn_formObat);
        pn_formObat.setLayout(pn_formObatLayout);
        pn_formObatLayout.setHorizontalGroup(
            pn_formObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        pn_formObatLayout.setVerticalGroup(
            pn_formObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        mainPanel.add(pn_formObat, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_dataObat;
    private javax.swing.JPanel pn_formObat;
    // End of variables declaration//GEN-END:variables
}
