/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

/**
 *
 * @author LENOVO
 */
public class FormDokter extends javax.swing.JPanel {

    /**
     * Creates new form FormDokter
     */
    public FormDokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pn_dataDokter = new javax.swing.JPanel();
        pn_formDokter = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pn_dataDokterLayout = new javax.swing.GroupLayout(pn_dataDokter);
        pn_dataDokter.setLayout(pn_dataDokterLayout);
        pn_dataDokterLayout.setHorizontalGroup(
            pn_dataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        pn_dataDokterLayout.setVerticalGroup(
            pn_dataDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        mainPanel.add(pn_dataDokter, "card2");

        javax.swing.GroupLayout pn_formDokterLayout = new javax.swing.GroupLayout(pn_formDokter);
        pn_formDokter.setLayout(pn_formDokterLayout);
        pn_formDokterLayout.setHorizontalGroup(
            pn_formDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        pn_formDokterLayout.setVerticalGroup(
            pn_formDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        mainPanel.add(pn_formDokter, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_dataDokter;
    private javax.swing.JPanel pn_formDokter;
    // End of variables declaration//GEN-END:variables
}
